# Generated by Django 2.1.7 on 2019-02-27 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.CharField(blank=True, max_length=20, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('upload_num', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'archives',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(blank=True, max_length=20, null=True)),
                ('channel', models.CharField(blank=True, max_length=20, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circular',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IosOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.CharField(blank=True, db_column='playerId', max_length=50, null=True)),
                ('orderid', models.CharField(blank=True, db_column='orderId', max_length=50, null=True)),
                ('propprice', models.DecimalField(blank=True, db_column='propPrice', decimal_places=2, max_digits=10, null=True)),
                ('channel', models.CharField(blank=True, max_length=20, null=True)),
                ('rechargetime', models.DateTimeField(blank=True, db_column='rechargeTime', null=True)),
            ],
            options={
                'db_table': 'ios_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerid', models.CharField(blank=True, db_column='playerId', max_length=50, null=True)),
                ('orderid', models.CharField(blank=True, db_column='orderId', max_length=64, null=True)),
                ('propname', models.CharField(blank=True, db_column='propName', max_length=64, null=True)),
                ('propnumber', models.IntegerField(blank=True, db_column='propNumber', null=True)),
                ('propprice', models.DecimalField(blank=True, db_column='propPrice', decimal_places=2, max_digits=10, null=True)),
                ('channelcode', models.CharField(blank=True, db_column='channelCode', max_length=64, null=True)),
                ('channellabel', models.CharField(blank=True, db_column='channelLabel', max_length=20, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('rechargetime', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('givingtime', models.DateTimeField(auto_now=True)),
                ('confirm', models.IntegerField(blank=True, null=True)),
                ('confirmtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('billno', models.CharField(blank=True, max_length=50, null=True)),
                ('account', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('uuid', models.CharField(blank=True, max_length=40, null=True)),
                ('roleid', models.CharField(blank=True, max_length=50, null=True)),
                ('zone', models.IntegerField(blank=True, null=True)),
                ('rechargetime', models.DateTimeField(blank=True, db_column='rechargeTime', null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('givingtime', models.DateTimeField(blank=True, db_column='givingTime', null=True)),
            ],
            options={
                'db_table': 'order_pp',
                'managed': False,
            },
        ),
    ]
